# Generated by Django 4.2.7 on 2025-06-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_delivery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiclemodel",
            options={
                "ordering": ["model", "number"],
                "verbose_name": "Модель транспорта",
                "verbose_name_plural": "Модели транспорта",
            },
        ),
        migrations.RemoveField(
            model_name="vehiclemodel",
            name="name",
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="model",
            field=models.CharField(default="", max_length=100, verbose_name="Модель"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="number",
            field=models.CharField(default="", max_length=100, verbose_name="Номер"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="vehicle_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="core.vehiclemodel",
                verbose_name="Модель транспорта (модель/номер)",
            ),
        ),
    ]
