# Generated by Django 4.2.7 on 2025-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_vehiclemodel_options_remove_vehiclemodel_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-departure_datetime", "id"],
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
            },
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="delivery_date",
        ),
        migrations.AddField(
            model_name="delivery",
            name="arrival_datetime",
            field=models.DateTimeField(
                default="2025-06-24 00:00:00", verbose_name="Дата и время доставки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="departure_datetime",
            field=models.DateTimeField(
                default="2025-06-25 00:00:00", verbose_name="Дата и время отправки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="transit_time",
            field=models.DurationField(default="24:00:00", verbose_name="Время в пути"),
            preserve_default=False,
        ),
    ]
