# Generated by Django 4.2.7 on 2025-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_delivery_options_remove_delivery_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="from_coords",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="Координаты отправления (lat,lon)",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="to_coords",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="Координаты назначения (lat,lon)",
            ),
        ),
    ]
